// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace refLinkApi.Migrations
{
    [DbContext(typeof(RefLinkContext))]
    [Migration("20240422131213_NewRef2")]
    partial class NewRef2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("refLinkApi.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostingId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("refLinkApi.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("refLinkApi.Models.Posting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("Postings");
                });

            modelBuilder.Entity("refLinkApi.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostingId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("refLinkApi.Models.Referencer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ResponseId");

                    b.ToTable("Referencers");
                });

            modelBuilder.Entity("refLinkApi.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("refLinkApi.Models.Candidate", b =>
                {
                    b.HasOne("refLinkApi.Models.Posting", null)
                        .WithMany("Candidates")
                        .HasForeignKey("PostingId");
                });

            modelBuilder.Entity("refLinkApi.Models.Posting", b =>
                {
                    b.HasOne("refLinkApi.Models.Employer", null)
                        .WithMany("Postings")
                        .HasForeignKey("EmployerId");
                });

            modelBuilder.Entity("refLinkApi.Models.Question", b =>
                {
                    b.HasOne("refLinkApi.Models.Posting", null)
                        .WithMany("Questions")
                        .HasForeignKey("PostingId");
                });

            modelBuilder.Entity("refLinkApi.Models.Referencer", b =>
                {
                    b.HasOne("refLinkApi.Models.Candidate", null)
                        .WithMany("Referencers")
                        .HasForeignKey("CandidateId");

                    b.HasOne("refLinkApi.Models.Response", "Response")
                        .WithMany()
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Response");
                });

            modelBuilder.Entity("refLinkApi.Models.Response", b =>
                {
                    b.HasOne("refLinkApi.Models.Question", null)
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("refLinkApi.Models.Candidate", b =>
                {
                    b.Navigation("Referencers");
                });

            modelBuilder.Entity("refLinkApi.Models.Employer", b =>
                {
                    b.Navigation("Postings");
                });

            modelBuilder.Entity("refLinkApi.Models.Posting", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("refLinkApi.Models.Question", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
