name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/azure-static-web-apps-icy-smoke-0b04e3303.yml
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/azure-static-web-apps-icy-smoke-0b04e3303.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # specify Node.js version here

      - name: Install dependencies
        run: npm install --prefix frontend

      - name: Build
        run: npm run build --prefix frontend
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_SMOKE_0B04E3303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/frontend" # App source code path
          api_location: "" # Api source code path - optional
          skip_api_build: true
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_SMOKE_0B04E3303 }}
          action: "close"
